// <auto-generated />
using System;
using BikeMap.Migrations;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Migrations.Migrations
{
    [DbContext(typeof(BikeMapDbContext))]
    [Migration("20260817061707_AddFeaturesTable")]
    partial class AddFeaturesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "feature_type_enum", new[] { "road", "path", "route" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BikeMap.Migrations.Feature", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Bicycle")
                        .HasColumnType("text")
                        .HasColumnName("bicycle");

                    b.Property<string>("CycleNetwork")
                        .HasColumnType("text")
                        .HasColumnName("cycle_network");

                    b.Property<string>("CyclewayLeft")
                        .HasColumnType("text")
                        .HasColumnName("cycleway_left");

                    b.Property<bool>("CyclewayLeftBuffer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cycleway_left_buffer");

                    b.Property<string>("CyclewayRight")
                        .HasColumnType("text")
                        .HasColumnName("cycleway_right");

                    b.Property<bool>("CyclewayRightBuffer")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("cycleway_right_buffer");

                    b.Property<FeatureType>("FeatureType")
                        .HasColumnType("feature_type_enum")
                        .HasColumnName("feature_type");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry(Geometry, 4326)")
                        .HasColumnName("geom");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<long>("OsmId")
                        .HasColumnType("bigint")
                        .HasColumnName("osm_id");

                    b.Property<string>("OsmType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("osm_type");

                    b.Property<string>("Ref")
                        .HasColumnType("text")
                        .HasColumnName("ref");

                    b.Property<string>("Route")
                        .HasColumnType("text")
                        .HasColumnName("route");

                    b.Property<string>("State")
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("tags")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.HasKey("Id");

                    b.HasIndex("FeatureType")
                        .HasDatabaseName("idx_features_feature_type");

                    b.HasIndex("Geom")
                        .HasDatabaseName("idx_features_geom");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Geom"), "GIST");

                    b.HasIndex("OsmType", "OsmId")
                        .IsUnique()
                        .HasDatabaseName("ux_features_osm_key");

                    b.ToTable("features", null, t =>
                        {
                            t.HasCheckConstraint("chk_features_geom_type", "GeometryType(geom) IN ('LINESTRING', 'MULTILINESTRING')");

                            t.HasCheckConstraint("chk_features_geom_valid", "ST_IsValid(geom)");

                            t.HasCheckConstraint("features_osm_type_check", "osm_type IN ('way', 'relation')");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
