name: Preprocess OSM Data
on:
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: bikemap-staging

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: install-aws-cli-action
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          arch: amd64

      - name: confirm aws cli version
        run: aws --version

      - name: "Checkout repo"
        uses: actions/checkout@v3

      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Install deps"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ./scripts

      # Runs a set of commands using the runners shell
      - name: "Run fetch_data.py"
        run: python fetch_data.py
        working-directory: ./scripts

      - name: "Upload to s3 bikemap container"
        run: aws s3 sync . s3://bikemap/
        working-directory: ./data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
