name: Preprocess OSM Data
on:
  schedule:
    cron: "0 0 * * *"

jobs:
  sync:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v3

      - run: "cd scripts"

      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: "Install deps"
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Runs a set of commands using the runners shell
      - name: "Run fetch_data.py"
        run: python fetch_data.py
